import os
import joblib
import pandas as pd
import numpy as np
import streamlit as st
import plotly.graph_objects as go

# --------------------------------------------------------------------------
# 1. PAGE CONFIGURATION & STYLING
# --------------------------------------------------------------------------
st.set_page_config(
    page_title="Customer Churn Intelligence Dashboard",
    page_icon="📊",
    layout="wide"
)

st.title("📊 Customer Churn Risk Intelligence Dashboard")
st.markdown("Interactively simulate customer attributes and evaluate real-time churn probabilities generated by the trained **XGBoost** model.")

# --------------------------------------------------------------------------
# 2. MODEL ARTIFACT LOADING WITH CACHING
# --------------------------------------------------------------------------
MODEL_PATH = os.path.join("models", "xgboost_churn_model.pkl")

@st.cache_resource
def load_churn_model():
    """Loads and caches the XGBoost model in RAM."""
    if not os.path.exists(MODEL_PATH):
        st.error(f"Model artifact not found at: {MODEL_PATH}")
        return None
    return joblib.load(MODEL_PATH)

model = load_churn_model()

# --------------------------------------------------------------------------
# 3. SIDEBAR INTERACTIVE CONTROLS
# --------------------------------------------------------------------------
st.sidebar.header("👤 Customer Demographics & Behavior")

age_std = st.sidebar.slider("Age (Normalized)", -2.5, 2.5, 0.5, step=0.1)
tenure_std = st.sidebar.slider("Tenure Months (Normalized)", -2.5, 2.5, -0.5, step=0.1)
monthly_charges_std = st.sidebar.slider("Monthly Charges (Normalized)", -2.5, 2.5, 1.2, step=0.1)
total_charges_std = st.sidebar.slider("Total Charges (Normalized)", -2.5, 2.5, -0.3, step=0.1)

st.sidebar.markdown("---")
st.sidebar.header("🎫 Engagement & Support Metrics")
tickets_std = st.sidebar.slider("Support Tickets 30d (Normalized)", -2.5, 2.5, 1.5, step=0.1)
logins_std = st.sidebar.slider("App Logins 30d (Normalized)", -2.5, 2.5, -0.8, step=0.1)

# Derived feature calculations
charge_per_login_std = monthly_charges_std - logins_std
ticket_ratio_std = tickets_std - tenure_std

st.sidebar.markdown("---")
st.sidebar.header("💳 Contract & Payment Method")
contract = st.sidebar.selectbox("Contract Type", ["Month-to-Month", "One-Year", "Two-Year"])
payment = st.sidebar.selectbox("Payment Method", ["Electronic Check", "Credit Card", "Bank Transfer / Other"])

# One-Hot Encoding mapping matching training columns
contract_one_year = 1 if contract == "One-Year" else 0
contract_two_year = 1 if contract == "Two-Year" else 0
payment_credit_card = 1 if payment == "Credit Card" else 0
payment_electronic_check = 1 if payment == "Electronic Check" else 0

# --------------------------------------------------------------------------
# 4. PREDICTION COMPUTATION
# --------------------------------------------------------------------------
input_dict = {
    "age": age_std,
    "tenure_months": tenure_std,
    "monthly_charges": monthly_charges_std,
    "total_charges": total_charges_std,
    "support_tickets_30d": tickets_std,
    "app_logins_30d": logins_std,
    "charge_per_login": charge_per_login_std,
    "ticket_ratio": ticket_ratio_std,
    "contract_type_One-Year": contract_one_year,
    "contract_type_Two-Year": contract_two_year,
    "payment_method_Credit Card": payment_credit_card,
    "payment_method_Electronic Check": payment_electronic_check
}

df_input = pd.DataFrame([input_dict])

if model is not None:
    probability = float(model.predict_proba(df_input)[0][1])
    prediction = int(model.predict(df_input)[0])

    # --------------------------------------------------------------------------
    # 5. DASHBOARD LAYOUT & VISUALIZATIONS
    # --------------------------------------------------------------------------
    col1, col2 = st.columns([1, 1])

    with col1:
        st.subheader("🎯 Real-Time Prediction Summary")
        
        # Risk Badge Alert
        if probability >= 0.70:
            st.error(f"🚨 **HIGH CHURN RISK** (Probability: {probability:.1%})")
            st.warning("Action Recommended: Trigger immediate retention intervention and issue a proactive discount offer.")
        elif probability >= 0.35:
            st.warning(f"⚠️ **MEDIUM CHURN RISK** (Probability: {probability:.1%})")
            st.info("Action Recommended: Queue automated product re-engagement email sequence.")
        else:
            st.success(f"✅ **LOW CHURN RISK** (Probability: {probability:.1%})")
            st.info("Action Recommended: Customer account is healthy. No intervention required.")

        # Metric Displays
        m1, m2, m3 = st.columns(3)
        m1.metric("Predicted Status", "Churn" if prediction == 1 else "Stay")
        m2.metric("Churn Risk Probability", f"{probability:.2%}")
        m3.metric("Ticket Ratio (Derived)", f"{ticket_ratio_std:.2f}")

    with col2:
            st.subheader("📈 Probability Gauge")
            
            fig = go.Figure(go.Indicator(
                mode="gauge+number",
                value=probability * 100,
                domain={'x': [0, 1], 'y': [0, 1]},
                title={'text': "Churn Probability Score (%)"},
                gauge={
                    'axis': {'range': [0, 100]},
                    'bar': {'color': "darkblue"},
                    'steps': [
                        {'range': [0, 35], 'color': "lightgreen"},
                        {'range': [35, 70], 'color': "khaki"},
                        {'range': [70, 100], 'color': "salmon"}
                    ],
                    'threshold': {
                        'line': {'color': "red", 'width': 4},
                        'thickness': 0.75,
                        'value': 70
                    }
                }
            ))
            # Updated to pass container width cleanly
            st.plotly_chart(fig, use_container_width=True)

    st.markdown("---")
    st.subheader("🔬 Evaluated Model Input Feature Vector")
    st.dataframe(df_input, use_container_width=True)
    
    # Display engineered feature matrix inspect table
